services:
  frontend:
    image: ghcr.io/ternaustralia/linkeddata-site:0.12.7-local.2.8b6d713
    container_name: linkeddata-site
    ports:
      - 8000:8000

  backend:
    image: ghcr.io/ternaustralia/linkeddata-api:0.7.2
    container_name: linkeddata-api
    ports:
      - 5000:5000

networks:
  default:
    name: dawe-rlp-vocabs_devcontainer_default
    external: true
