services:
  frontend:
    image: ghcr.io/ternaustralia/linkeddata-site:0.9.1-local.7.4345d09
    container_name: linkeddata-site
    ports:
      - 8000:8000

  backend:
    image: ghcr.io/ternaustralia/linkeddata-api:latest
    container_name: linkeddata-api
    ports:
      - 5000:5000

  graphdb:
    image: ghcr.io/ternaustralia/graphdb:9.10.3-free
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 7200:7200
