# This workflow runs every 30 minutes and checks
# if there are any changes in upstream LUTs.
name: Check upstream LUTs for changes

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check_luts_for_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Install project
        run: pip install .

      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI_FOR_UPSTREAM_LUTS }}

      - name: Check for changes in upstream LUTs
        run: python luts.py --path remote_data_dir --validate
