name: Publish on release to GraphDB

on:
  release:
    types: [released, prereleased]

env:
  PYTHON_VERSION: "3.10"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Install project
        run: pip install .

      - name: Expand the graph data and write to vocab_files/ - Observable Properties
        run: python expand.py OP vocab_files/expanded-triples-dump-op.ttl

      - name: Expand the graph data and write to vocab_files/ - LUTs
        run: python expand.py LUT vocab_files/expanded-triples-dump-lut.ttl

      - name: Expand the graph data and write to vocab_files/ - Attributes
        run: python expand.py A vocab_files/expanded-triples-dump-attributes.ttl

      - name: Expand the graph data and write to vocab_files/ - Methods
        run: python expand.py M vocab_files/expanded-triples-dump-methods.ttl

      - name: Load data to GraphDB
        run: python load.py --url https://graphdb.tern.org.au --username ${{ secrets.GRAPHDB_USERNAME }} --password ${{ secrets.GRAPHDB_PASSWORD }}
